### ISSUE TITLE
Required Parameters

### ISSUE THREAD

**Issue by ranimaniyan** [dranes/omnipay-ippay#3]
What are the parameters we need to pass to test this application? can you please mention it in README file? For example: Make a purchase with CARD.

**Comment by dranes** [comment]
@ranimaniyan I will put some examples today in the Readme

**Comment by dranes** [comment]
@ranimaniyan there you go https://github.com/dranes/omnipay-ippay/blob/master/README.md

I hope that helps you.

**Comment by ranimaniyan** [comment]
@dranes Thank you so much. It helps me a lot
